package frontend

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/gallowaysoftware/vibe/internal/vibe/mcp"
	"github.com/gallowaysoftware/vibe/internal/vibe/profile"
)

// activateExternal renders frontend.template (with ${VAR} substitution and
// any frontend.mcps merged in) to frontend.write_file. The user is then
// responsible for launching their tool against the resulting config.
func activateExternal(p *profile.Profile, ctx profile.ExpandContext) (*Result, error) {
	resolved, env, err := writeFrontendConfig(p, &ctx)
	if err != nil {
		return nil, err
	}
	return &Result{
		WroteFile:       resolved,
		RestartRequired: p.Frontend.RestartRequired,
		Env:             env,
		Kind:            profile.FrontendExternal,
	}, nil
}

// writeFrontendConfig renders the profile's frontend.template (with
// frontend.mcps merged in) to frontend.write_file. Returns the resolved
// path and the expanded env block so the caller can use them in the
// Result it returns (external) or pass them through to a child process
// (managed). When write_file is empty this is a no-op that still returns
// the expanded env — useful for managed frontends that just want to
// inherit OPENCODE_CONFIG-style variables without writing a file.
//
// The ctx pointer is mutated so subsequent template expansions (e.g.
// frontend.env that references ${WRITE_FILE}) see the resolved path.
func writeFrontendConfig(p *profile.Profile, ctx *profile.ExpandContext) (string, map[string]string, error) {
	specs := p.Frontend.WriteFileSpecs()

	// Resolve every target path first so ${WRITE_FILE} in env expansion
	// points at the primary (first) file, preserving single-file behavior
	// for existing profiles that reference it.
	resolved := make([]string, len(specs))
	// Validation rejects literal duplicate targets, but ${VAR} expansion can
	// still land two entries on the same file — catch that here so one render
	// doesn't silently clobber another.
	firstAt := make(map[string]int, len(specs))
	for i, spec := range specs {
		r, err := profile.ExpandPathString(spec.Path, *ctx)
		if err != nil {
			return "", nil, fmt.Errorf("expand write target %q: %w", spec.Path, err)
		}
		if j, dup := firstAt[filepath.Clean(r)]; dup {
			return "", nil, fmt.Errorf("write_files: %q resolves to %q, same file as entry %d", spec.Path, r, j)
		}
		firstAt[filepath.Clean(r)] = i
		resolved[i] = r
	}
	if len(resolved) > 0 {
		ctx.WriteFile = resolved[0]
	}

	env, err := p.ExpandEnv(*ctx)
	if err != nil {
		return "", nil, fmt.Errorf("expand env: %w", err)
	}

	if len(specs) == 0 {
		// No file to write — managed kind without a template just gets the
		// expanded env back.
		return "", env, nil
	}

	for i, spec := range specs {
		if err := renderConfigFile(spec, resolved[i], *ctx); err != nil {
			return "", nil, err
		}
	}
	return resolved[0], env, nil
}

// renderConfigFile expands one WriteFileSpec's template (merging any per-spec
// MCPs under a top-level "mcp" key) and writes it to resolved. Shared by the
// single-file (legacy write_file) and multi-file (write_files) paths.
func renderConfigFile(spec profile.WriteFileSpec, resolved string, ctx profile.ExpandContext) error {
	expanded, err := profile.ExpandTemplate(spec.Template, ctx)
	if err != nil {
		return fmt.Errorf("expand template for %s: %w", resolved, err)
	}

	if len(spec.MCPs) > 0 {
		if _, exists := expanded["mcp"]; exists {
			return fmt.Errorf("template for %s already defines top-level %q key; cannot merge with mcps", resolved, "mcp")
		}
		mcpSpecs, err := mcp.LoadMany(spec.MCPs)
		if err != nil {
			return fmt.Errorf("load mcps: %w", err)
		}
		mcpBlock := make(map[string]any, len(mcpSpecs))
		for name, m := range mcpSpecs {
			mcpBlock[name] = m
		}
		expanded["mcp"] = mcpBlock
	}

	body, err := json.MarshalIndent(expanded, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal template for %s: %w", resolved, err)
	}
	if err := os.MkdirAll(filepath.Dir(resolved), 0o755); err != nil {
		return fmt.Errorf("mkdir for %s: %w", resolved, err)
	}
	// Skip the leading "# Generated by vibe ..." header when the
	// resolved path is a strict-JSON file (e.g., pi's models.json).
	// JSON5-lenient consumers (opencode) tolerate the `#` line; strict
	// consumers (pi.dev) bail. The marshaled body is always JSON, so
	// the header has always been technically invalid — historically
	// it was load-bearing only as a human "don't edit" warning, which
	// vibe-generated files already convey by being regenerated on
	// every `vibe start`. For non-JSON extensions (e.g. oh-my-pi's
	// models.yml / config.yml — JSON is a YAML subset) keep the header.
	out := body
	if filepath.Ext(resolved) != ".json" {
		out = append([]byte("# Generated by vibe — do not edit. Will be overwritten on `vibe start`.\n"), body...)
	}
	// 0600: the rendered config can merge credential specs (API keys,
	// tokens) from mcps or provider blocks, so it must not be world/group
	// readable.
	if err := os.WriteFile(resolved, append(out, '\n'), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", resolved, err)
	}
	return nil
}
