package frontend

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/gallowaysoftware/vibe/internal/vibe/mcp"
	"github.com/gallowaysoftware/vibe/internal/vibe/profile"
)

// activateExternal renders frontend.template (with ${VAR} substitution and
// any frontend.mcps merged in) to frontend.write_file. The user is then
// responsible for launching their tool against the resulting config.
func activateExternal(p *profile.Profile, ctx profile.ExpandContext) (*Result, error) {
	resolved, env, err := writeFrontendConfig(p, &ctx)
	if err != nil {
		return nil, err
	}
	return &Result{
		WroteFile:       resolved,
		RestartRequired: p.Frontend.RestartRequired,
		Env:             env,
		Kind:            profile.FrontendExternal,
	}, nil
}

// writeFrontendConfig renders the profile's frontend.template (with
// frontend.mcps merged in) to frontend.write_file. Returns the resolved
// path and the expanded env block so the caller can use them in the
// Result it returns (external) or pass them through to a child process
// (managed). When write_file is empty this is a no-op that still returns
// the expanded env — useful for managed frontends that just want to
// inherit OPENCODE_CONFIG-style variables without writing a file.
//
// The ctx pointer is mutated so subsequent template expansions (e.g.
// frontend.env that references ${WRITE_FILE}) see the resolved path.
func writeFrontendConfig(p *profile.Profile, ctx *profile.ExpandContext) (string, map[string]string, error) {
	var resolved string
	if p.Frontend.WriteFile != "" {
		r, err := profile.ExpandPathString(p.Frontend.WriteFile, *ctx)
		if err != nil {
			return "", nil, fmt.Errorf("expand write_file: %w", err)
		}
		resolved = r
		ctx.WriteFile = resolved
	}

	env, err := p.ExpandEnv(*ctx)
	if err != nil {
		return "", nil, fmt.Errorf("expand env: %w", err)
	}

	if resolved == "" {
		// No file to write — managed kind without a template just gets the
		// expanded env back.
		return "", env, nil
	}

	expanded, err := p.ExpandTemplate(*ctx)
	if err != nil {
		return "", nil, fmt.Errorf("expand template: %w", err)
	}

	if len(p.Frontend.MCPs) > 0 {
		if _, exists := expanded["mcp"]; exists {
			return "", nil, fmt.Errorf("frontend.template already defines top-level %q key; cannot merge with frontend.mcps", "mcp")
		}
		specs, err := mcp.LoadMany(p.Frontend.MCPs)
		if err != nil {
			return "", nil, fmt.Errorf("load mcps: %w", err)
		}
		mcpBlock := make(map[string]any, len(specs))
		for name, spec := range specs {
			mcpBlock[name] = spec
		}
		expanded["mcp"] = mcpBlock
	}

	body, err := json.MarshalIndent(expanded, "", "  ")
	if err != nil {
		return "", nil, fmt.Errorf("marshal template: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(resolved), 0o755); err != nil {
		return "", nil, fmt.Errorf("mkdir for %s: %w", resolved, err)
	}
	// Skip the leading "# Generated by vibe ..." header when the
	// resolved path is a strict-JSON file (e.g., pi's models.json).
	// JSON5-lenient consumers (opencode) tolerate the `#` line; strict
	// consumers (pi.dev) bail. The marshaled body is always JSON, so
	// the header has always been technically invalid — historically
	// it was load-bearing only as a human "don't edit" warning, which
	// vibe-generated files already convey by being regenerated on
	// every `vibe start`. For non-JSON extensions (none today, but
	// future YAML/TOML templates would qualify) keep the header.
	out := body
	if filepath.Ext(resolved) != ".json" {
		out = append([]byte("# Generated by vibe — do not edit. Will be overwritten on `vibe start`.\n"), body...)
	}
	if err := os.WriteFile(resolved, append(out, '\n'), 0o644); err != nil {
		return "", nil, fmt.Errorf("write %s: %w", resolved, err)
	}
	return resolved, env, nil
}
