// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: vibe/v1/control.proto

package vibev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gallowaysoftware/vibe/proto/vibe/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ControlServiceName is the fully-qualified name of the ControlService service.
	ControlServiceName = "vibe.v1.ControlService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ControlServiceStatusProcedure is the fully-qualified name of the ControlService's Status RPC.
	ControlServiceStatusProcedure = "/vibe.v1.ControlService/Status"
	// ControlServiceListProfilesProcedure is the fully-qualified name of the ControlService's
	// ListProfiles RPC.
	ControlServiceListProfilesProcedure = "/vibe.v1.ControlService/ListProfiles"
	// ControlServiceStartProcedure is the fully-qualified name of the ControlService's Start RPC.
	ControlServiceStartProcedure = "/vibe.v1.ControlService/Start"
	// ControlServiceStopProcedure is the fully-qualified name of the ControlService's Stop RPC.
	ControlServiceStopProcedure = "/vibe.v1.ControlService/Stop"
	// ControlServiceShutdownProcedure is the fully-qualified name of the ControlService's Shutdown RPC.
	ControlServiceShutdownProcedure = "/vibe.v1.ControlService/Shutdown"
	// ControlServiceLogsProcedure is the fully-qualified name of the ControlService's Logs RPC.
	ControlServiceLogsProcedure = "/vibe.v1.ControlService/Logs"
	// ControlServicePullProcedure is the fully-qualified name of the ControlService's Pull RPC.
	ControlServicePullProcedure = "/vibe.v1.ControlService/Pull"
	// ControlServiceCellDrainProcedure is the fully-qualified name of the ControlService's CellDrain
	// RPC.
	ControlServiceCellDrainProcedure = "/vibe.v1.ControlService/CellDrain"
	// ControlServiceCellResumeProcedure is the fully-qualified name of the ControlService's CellResume
	// RPC.
	ControlServiceCellResumeProcedure = "/vibe.v1.ControlService/CellResume"
)

// ControlServiceClient is a client for the vibe.v1.ControlService service.
type ControlServiceClient interface {
	// Status returns the daemon's current state.
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// ListProfiles enumerates the profiles vibe knows about.
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	// Start activates the named profile. Returns once it's ready (or errors).
	Start(context.Context, *connect.Request[v1.StartRequest]) (*connect.Response[v1.StartResponse], error)
	// Stop deactivates the currently-active profile. No-op if nothing active.
	Stop(context.Context, *connect.Request[v1.StopRequest]) (*connect.Response[v1.StopResponse], error)
	// Shutdown asks the daemon to exit gracefully.
	Shutdown(context.Context, *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error)
	// Logs returns the most recent llama-server log lines. Streaming follow is
	// a future RPC.
	Logs(context.Context, *connect.Request[v1.LogsRequest]) (*connect.Response[v1.LogsResponse], error)
	// Pull downloads the profile's model from HuggingFace if it isn't already
	// present locally. Returns a single PHASE_DONE message if the model is
	// already cached at the expected size, or a stream of PHASE_DOWNLOADING
	// updates while bytes flow in.
	Pull(context.Context, *connect.Request[v1.PullRequest]) (*connect.ServerStreamForClient[v1.PullProgress], error)
	// CellDrain runs this daemon's configured drain command (cell_cmds.drain)
	// — the fleet-control "reclaim this box" verb (fleet-control C2). It
	// reports what was resident/in-flight BEFORE draining so the caller can
	// show the pre-drain report. FailedPrecondition when the daemon has no
	// cell verbs configured; Unavailable (with stderr) when the command
	// fails. Acts on the daemon's OWN local cell — remote reach comes from
	// calling a remote daemon, not from routing here.
	CellDrain(context.Context, *connect.Request[v1.CellDrainRequest]) (*connect.Response[v1.CellDrainResponse], error)
	// CellResume runs cell_cmds.resume, restoring JIT service after a drain.
	// Same error contract as CellDrain.
	CellResume(context.Context, *connect.Request[v1.CellResumeRequest]) (*connect.Response[v1.CellResumeResponse], error)
}

// NewControlServiceClient constructs a client for the vibe.v1.ControlService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewControlServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ControlServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	controlServiceMethods := v1.File_vibe_v1_control_proto.Services().ByName("ControlService").Methods()
	return &controlServiceClient{
		status: connect.NewClient[v1.StatusRequest, v1.StatusResponse](
			httpClient,
			baseURL+ControlServiceStatusProcedure,
			connect.WithSchema(controlServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		listProfiles: connect.NewClient[v1.ListProfilesRequest, v1.ListProfilesResponse](
			httpClient,
			baseURL+ControlServiceListProfilesProcedure,
			connect.WithSchema(controlServiceMethods.ByName("ListProfiles")),
			connect.WithClientOptions(opts...),
		),
		start: connect.NewClient[v1.StartRequest, v1.StartResponse](
			httpClient,
			baseURL+ControlServiceStartProcedure,
			connect.WithSchema(controlServiceMethods.ByName("Start")),
			connect.WithClientOptions(opts...),
		),
		stop: connect.NewClient[v1.StopRequest, v1.StopResponse](
			httpClient,
			baseURL+ControlServiceStopProcedure,
			connect.WithSchema(controlServiceMethods.ByName("Stop")),
			connect.WithClientOptions(opts...),
		),
		shutdown: connect.NewClient[v1.ShutdownRequest, v1.ShutdownResponse](
			httpClient,
			baseURL+ControlServiceShutdownProcedure,
			connect.WithSchema(controlServiceMethods.ByName("Shutdown")),
			connect.WithClientOptions(opts...),
		),
		logs: connect.NewClient[v1.LogsRequest, v1.LogsResponse](
			httpClient,
			baseURL+ControlServiceLogsProcedure,
			connect.WithSchema(controlServiceMethods.ByName("Logs")),
			connect.WithClientOptions(opts...),
		),
		pull: connect.NewClient[v1.PullRequest, v1.PullProgress](
			httpClient,
			baseURL+ControlServicePullProcedure,
			connect.WithSchema(controlServiceMethods.ByName("Pull")),
			connect.WithClientOptions(opts...),
		),
		cellDrain: connect.NewClient[v1.CellDrainRequest, v1.CellDrainResponse](
			httpClient,
			baseURL+ControlServiceCellDrainProcedure,
			connect.WithSchema(controlServiceMethods.ByName("CellDrain")),
			connect.WithClientOptions(opts...),
		),
		cellResume: connect.NewClient[v1.CellResumeRequest, v1.CellResumeResponse](
			httpClient,
			baseURL+ControlServiceCellResumeProcedure,
			connect.WithSchema(controlServiceMethods.ByName("CellResume")),
			connect.WithClientOptions(opts...),
		),
	}
}

// controlServiceClient implements ControlServiceClient.
type controlServiceClient struct {
	status       *connect.Client[v1.StatusRequest, v1.StatusResponse]
	listProfiles *connect.Client[v1.ListProfilesRequest, v1.ListProfilesResponse]
	start        *connect.Client[v1.StartRequest, v1.StartResponse]
	stop         *connect.Client[v1.StopRequest, v1.StopResponse]
	shutdown     *connect.Client[v1.ShutdownRequest, v1.ShutdownResponse]
	logs         *connect.Client[v1.LogsRequest, v1.LogsResponse]
	pull         *connect.Client[v1.PullRequest, v1.PullProgress]
	cellDrain    *connect.Client[v1.CellDrainRequest, v1.CellDrainResponse]
	cellResume   *connect.Client[v1.CellResumeRequest, v1.CellResumeResponse]
}

// Status calls vibe.v1.ControlService.Status.
func (c *controlServiceClient) Status(ctx context.Context, req *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// ListProfiles calls vibe.v1.ControlService.ListProfiles.
func (c *controlServiceClient) ListProfiles(ctx context.Context, req *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return c.listProfiles.CallUnary(ctx, req)
}

// Start calls vibe.v1.ControlService.Start.
func (c *controlServiceClient) Start(ctx context.Context, req *connect.Request[v1.StartRequest]) (*connect.Response[v1.StartResponse], error) {
	return c.start.CallUnary(ctx, req)
}

// Stop calls vibe.v1.ControlService.Stop.
func (c *controlServiceClient) Stop(ctx context.Context, req *connect.Request[v1.StopRequest]) (*connect.Response[v1.StopResponse], error) {
	return c.stop.CallUnary(ctx, req)
}

// Shutdown calls vibe.v1.ControlService.Shutdown.
func (c *controlServiceClient) Shutdown(ctx context.Context, req *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error) {
	return c.shutdown.CallUnary(ctx, req)
}

// Logs calls vibe.v1.ControlService.Logs.
func (c *controlServiceClient) Logs(ctx context.Context, req *connect.Request[v1.LogsRequest]) (*connect.Response[v1.LogsResponse], error) {
	return c.logs.CallUnary(ctx, req)
}

// Pull calls vibe.v1.ControlService.Pull.
func (c *controlServiceClient) Pull(ctx context.Context, req *connect.Request[v1.PullRequest]) (*connect.ServerStreamForClient[v1.PullProgress], error) {
	return c.pull.CallServerStream(ctx, req)
}

// CellDrain calls vibe.v1.ControlService.CellDrain.
func (c *controlServiceClient) CellDrain(ctx context.Context, req *connect.Request[v1.CellDrainRequest]) (*connect.Response[v1.CellDrainResponse], error) {
	return c.cellDrain.CallUnary(ctx, req)
}

// CellResume calls vibe.v1.ControlService.CellResume.
func (c *controlServiceClient) CellResume(ctx context.Context, req *connect.Request[v1.CellResumeRequest]) (*connect.Response[v1.CellResumeResponse], error) {
	return c.cellResume.CallUnary(ctx, req)
}

// ControlServiceHandler is an implementation of the vibe.v1.ControlService service.
type ControlServiceHandler interface {
	// Status returns the daemon's current state.
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// ListProfiles enumerates the profiles vibe knows about.
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	// Start activates the named profile. Returns once it's ready (or errors).
	Start(context.Context, *connect.Request[v1.StartRequest]) (*connect.Response[v1.StartResponse], error)
	// Stop deactivates the currently-active profile. No-op if nothing active.
	Stop(context.Context, *connect.Request[v1.StopRequest]) (*connect.Response[v1.StopResponse], error)
	// Shutdown asks the daemon to exit gracefully.
	Shutdown(context.Context, *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error)
	// Logs returns the most recent llama-server log lines. Streaming follow is
	// a future RPC.
	Logs(context.Context, *connect.Request[v1.LogsRequest]) (*connect.Response[v1.LogsResponse], error)
	// Pull downloads the profile's model from HuggingFace if it isn't already
	// present locally. Returns a single PHASE_DONE message if the model is
	// already cached at the expected size, or a stream of PHASE_DOWNLOADING
	// updates while bytes flow in.
	Pull(context.Context, *connect.Request[v1.PullRequest], *connect.ServerStream[v1.PullProgress]) error
	// CellDrain runs this daemon's configured drain command (cell_cmds.drain)
	// — the fleet-control "reclaim this box" verb (fleet-control C2). It
	// reports what was resident/in-flight BEFORE draining so the caller can
	// show the pre-drain report. FailedPrecondition when the daemon has no
	// cell verbs configured; Unavailable (with stderr) when the command
	// fails. Acts on the daemon's OWN local cell — remote reach comes from
	// calling a remote daemon, not from routing here.
	CellDrain(context.Context, *connect.Request[v1.CellDrainRequest]) (*connect.Response[v1.CellDrainResponse], error)
	// CellResume runs cell_cmds.resume, restoring JIT service after a drain.
	// Same error contract as CellDrain.
	CellResume(context.Context, *connect.Request[v1.CellResumeRequest]) (*connect.Response[v1.CellResumeResponse], error)
}

// NewControlServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewControlServiceHandler(svc ControlServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	controlServiceMethods := v1.File_vibe_v1_control_proto.Services().ByName("ControlService").Methods()
	controlServiceStatusHandler := connect.NewUnaryHandler(
		ControlServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(controlServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	controlServiceListProfilesHandler := connect.NewUnaryHandler(
		ControlServiceListProfilesProcedure,
		svc.ListProfiles,
		connect.WithSchema(controlServiceMethods.ByName("ListProfiles")),
		connect.WithHandlerOptions(opts...),
	)
	controlServiceStartHandler := connect.NewUnaryHandler(
		ControlServiceStartProcedure,
		svc.Start,
		connect.WithSchema(controlServiceMethods.ByName("Start")),
		connect.WithHandlerOptions(opts...),
	)
	controlServiceStopHandler := connect.NewUnaryHandler(
		ControlServiceStopProcedure,
		svc.Stop,
		connect.WithSchema(controlServiceMethods.ByName("Stop")),
		connect.WithHandlerOptions(opts...),
	)
	controlServiceShutdownHandler := connect.NewUnaryHandler(
		ControlServiceShutdownProcedure,
		svc.Shutdown,
		connect.WithSchema(controlServiceMethods.ByName("Shutdown")),
		connect.WithHandlerOptions(opts...),
	)
	controlServiceLogsHandler := connect.NewUnaryHandler(
		ControlServiceLogsProcedure,
		svc.Logs,
		connect.WithSchema(controlServiceMethods.ByName("Logs")),
		connect.WithHandlerOptions(opts...),
	)
	controlServicePullHandler := connect.NewServerStreamHandler(
		ControlServicePullProcedure,
		svc.Pull,
		connect.WithSchema(controlServiceMethods.ByName("Pull")),
		connect.WithHandlerOptions(opts...),
	)
	controlServiceCellDrainHandler := connect.NewUnaryHandler(
		ControlServiceCellDrainProcedure,
		svc.CellDrain,
		connect.WithSchema(controlServiceMethods.ByName("CellDrain")),
		connect.WithHandlerOptions(opts...),
	)
	controlServiceCellResumeHandler := connect.NewUnaryHandler(
		ControlServiceCellResumeProcedure,
		svc.CellResume,
		connect.WithSchema(controlServiceMethods.ByName("CellResume")),
		connect.WithHandlerOptions(opts...),
	)
	return "/vibe.v1.ControlService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ControlServiceStatusProcedure:
			controlServiceStatusHandler.ServeHTTP(w, r)
		case ControlServiceListProfilesProcedure:
			controlServiceListProfilesHandler.ServeHTTP(w, r)
		case ControlServiceStartProcedure:
			controlServiceStartHandler.ServeHTTP(w, r)
		case ControlServiceStopProcedure:
			controlServiceStopHandler.ServeHTTP(w, r)
		case ControlServiceShutdownProcedure:
			controlServiceShutdownHandler.ServeHTTP(w, r)
		case ControlServiceLogsProcedure:
			controlServiceLogsHandler.ServeHTTP(w, r)
		case ControlServicePullProcedure:
			controlServicePullHandler.ServeHTTP(w, r)
		case ControlServiceCellDrainProcedure:
			controlServiceCellDrainHandler.ServeHTTP(w, r)
		case ControlServiceCellResumeProcedure:
			controlServiceCellResumeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedControlServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedControlServiceHandler struct{}

func (UnimplementedControlServiceHandler) Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vibe.v1.ControlService.Status is not implemented"))
}

func (UnimplementedControlServiceHandler) ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vibe.v1.ControlService.ListProfiles is not implemented"))
}

func (UnimplementedControlServiceHandler) Start(context.Context, *connect.Request[v1.StartRequest]) (*connect.Response[v1.StartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vibe.v1.ControlService.Start is not implemented"))
}

func (UnimplementedControlServiceHandler) Stop(context.Context, *connect.Request[v1.StopRequest]) (*connect.Response[v1.StopResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vibe.v1.ControlService.Stop is not implemented"))
}

func (UnimplementedControlServiceHandler) Shutdown(context.Context, *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vibe.v1.ControlService.Shutdown is not implemented"))
}

func (UnimplementedControlServiceHandler) Logs(context.Context, *connect.Request[v1.LogsRequest]) (*connect.Response[v1.LogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vibe.v1.ControlService.Logs is not implemented"))
}

func (UnimplementedControlServiceHandler) Pull(context.Context, *connect.Request[v1.PullRequest], *connect.ServerStream[v1.PullProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("vibe.v1.ControlService.Pull is not implemented"))
}

func (UnimplementedControlServiceHandler) CellDrain(context.Context, *connect.Request[v1.CellDrainRequest]) (*connect.Response[v1.CellDrainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vibe.v1.ControlService.CellDrain is not implemented"))
}

func (UnimplementedControlServiceHandler) CellResume(context.Context, *connect.Request[v1.CellResumeRequest]) (*connect.Response[v1.CellResumeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vibe.v1.ControlService.CellResume is not implemented"))
}
