// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vibe/v1/control.proto

package vibev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Running     bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Ready       bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Profile     string                 `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	BackendAddr string                 `protobuf:"bytes,5,opt,name=backend_addr,json=backendAddr,proto3" json:"backend_addr,omitempty"`
	ProxyAddr   string                 `protobuf:"bytes,6,opt,name=proxy_addr,json=proxyAddr,proto3" json:"proxy_addr,omitempty"`
	Pid         int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	// frontend_env carries the env vars the user should set when launching the
	// external frontend, so `vibe env` can echo them after the fact.
	FrontendEnv   map[string]string `protobuf:"bytes,8,rep,name=frontend_env,json=frontendEnv,proto3" json:"frontend_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_vibe_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *Status) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Status) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Status) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Status) GetBackendAddr() string {
	if x != nil {
		return x.BackendAddr
	}
	return ""
}

func (x *Status) GetProxyAddr() string {
	if x != nil {
		return x.ProxyAddr
	}
	return ""
}

func (x *Status) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Status) GetFrontendEnv() map[string]string {
	if x != nil {
		return x.FrontendEnv
	}
	return nil
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_vibe_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Profile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FrontendInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	App             string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	WroteFile       string                 `protobuf:"bytes,2,opt,name=wrote_file,json=wroteFile,proto3" json:"wrote_file,omitempty"`
	RestartRequired bool                   `protobuf:"varint,3,opt,name=restart_required,json=restartRequired,proto3" json:"restart_required,omitempty"`
	// env_vars the user should set when launching the external frontend.
	// Example: {"OPENCODE_CONFIG": "/home/.../state/vibe/frontend/code/opencode.json"}.
	EnvVars       map[string]string `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendInfo) Reset() {
	*x = FrontendInfo{}
	mi := &file_vibe_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendInfo) ProtoMessage() {}

func (x *FrontendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendInfo.ProtoReflect.Descriptor instead.
func (*FrontendInfo) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *FrontendInfo) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *FrontendInfo) GetWroteFile() string {
	if x != nil {
		return x.WroteFile
	}
	return ""
}

func (x *FrontendInfo) GetRestartRequired() bool {
	if x != nil {
		return x.RestartRequired
	}
	return false
}

func (x *FrontendInfo) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{3}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{5}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ListProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *StartRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Frontend      *FrontendInfo          `protobuf:"bytes,2,opt,name=frontend,proto3" json:"frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *StartResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StartResponse) GetFrontend() *FrontendInfo {
	if x != nil {
		return x.Frontend
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{9}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *StopResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{11}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{12}
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{13}
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *LogsResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_vibe_v1_control_proto protoreflect.FileDescriptor

const file_vibe_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x15vibe/v1/control.proto\x12\avibe.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x02\n" +
	"\x06Status\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12!\n" +
	"\fbackend_addr\x18\x05 \x01(\tR\vbackendAddr\x12\x1d\n" +
	"\n" +
	"proxy_addr\x18\x06 \x01(\tR\tproxyAddr\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12C\n" +
	"\ffrontend_env\x18\b \x03(\v2 .vibe.v1.Status.FrontendEnvEntryR\vfrontendEnv\x1a>\n" +
	"\x10FrontendEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\xe5\x01\n" +
	"\fFrontendInfo\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x1d\n" +
	"\n" +
	"wrote_file\x18\x02 \x01(\tR\twroteFile\x12)\n" +
	"\x10restart_required\x18\x03 \x01(\bR\x0frestartRequired\x12=\n" +
	"\benv_vars\x18\x04 \x03(\v2\".vibe.v1.FrontendInfo.EnvVarsEntryR\aenvVars\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rStatusRequest\"9\n" +
	"\x0eStatusResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.vibe.v1.StatusR\x06status\"\x15\n" +
	"\x13ListProfilesRequest\"D\n" +
	"\x14ListProfilesResponse\x12,\n" +
	"\bprofiles\x18\x01 \x03(\v2\x10.vibe.v1.ProfileR\bprofiles\"(\n" +
	"\fStartRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"k\n" +
	"\rStartResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.vibe.v1.StatusR\x06status\x121\n" +
	"\bfrontend\x18\x02 \x01(\v2\x15.vibe.v1.FrontendInfoR\bfrontend\"\r\n" +
	"\vStopRequest\"7\n" +
	"\fStopResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.vibe.v1.StatusR\x06status\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\r\n" +
	"\vLogsRequest\"$\n" +
	"\fLogsResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines2\x87\x03\n" +
	"\x0eControlService\x12;\n" +
	"\x06Status\x12\x16.vibe.v1.StatusRequest\x1a\x17.vibe.v1.StatusResponse\"\x00\x12M\n" +
	"\fListProfiles\x12\x1c.vibe.v1.ListProfilesRequest\x1a\x1d.vibe.v1.ListProfilesResponse\"\x00\x128\n" +
	"\x05Start\x12\x15.vibe.v1.StartRequest\x1a\x16.vibe.v1.StartResponse\"\x00\x125\n" +
	"\x04Stop\x12\x14.vibe.v1.StopRequest\x1a\x15.vibe.v1.StopResponse\"\x00\x12A\n" +
	"\bShutdown\x12\x18.vibe.v1.ShutdownRequest\x1a\x19.vibe.v1.ShutdownResponse\"\x00\x125\n" +
	"\x04Logs\x12\x14.vibe.v1.LogsRequest\x1a\x15.vibe.v1.LogsResponse\"\x00B7Z5github.com/gallowaysoftware/vibe/proto/vibe/v1;vibev1b\x06proto3"

var (
	file_vibe_v1_control_proto_rawDescOnce sync.Once
	file_vibe_v1_control_proto_rawDescData []byte
)

func file_vibe_v1_control_proto_rawDescGZIP() []byte {
	file_vibe_v1_control_proto_rawDescOnce.Do(func() {
		file_vibe_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vibe_v1_control_proto_rawDesc), len(file_vibe_v1_control_proto_rawDesc)))
	})
	return file_vibe_v1_control_proto_rawDescData
}

var file_vibe_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_vibe_v1_control_proto_goTypes = []any{
	(*Status)(nil),                // 0: vibe.v1.Status
	(*Profile)(nil),               // 1: vibe.v1.Profile
	(*FrontendInfo)(nil),          // 2: vibe.v1.FrontendInfo
	(*StatusRequest)(nil),         // 3: vibe.v1.StatusRequest
	(*StatusResponse)(nil),        // 4: vibe.v1.StatusResponse
	(*ListProfilesRequest)(nil),   // 5: vibe.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),  // 6: vibe.v1.ListProfilesResponse
	(*StartRequest)(nil),          // 7: vibe.v1.StartRequest
	(*StartResponse)(nil),         // 8: vibe.v1.StartResponse
	(*StopRequest)(nil),           // 9: vibe.v1.StopRequest
	(*StopResponse)(nil),          // 10: vibe.v1.StopResponse
	(*ShutdownRequest)(nil),       // 11: vibe.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 12: vibe.v1.ShutdownResponse
	(*LogsRequest)(nil),           // 13: vibe.v1.LogsRequest
	(*LogsResponse)(nil),          // 14: vibe.v1.LogsResponse
	nil,                           // 15: vibe.v1.Status.FrontendEnvEntry
	nil,                           // 16: vibe.v1.FrontendInfo.EnvVarsEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_vibe_v1_control_proto_depIdxs = []int32{
	17, // 0: vibe.v1.Status.started_at:type_name -> google.protobuf.Timestamp
	15, // 1: vibe.v1.Status.frontend_env:type_name -> vibe.v1.Status.FrontendEnvEntry
	16, // 2: vibe.v1.FrontendInfo.env_vars:type_name -> vibe.v1.FrontendInfo.EnvVarsEntry
	0,  // 3: vibe.v1.StatusResponse.status:type_name -> vibe.v1.Status
	1,  // 4: vibe.v1.ListProfilesResponse.profiles:type_name -> vibe.v1.Profile
	0,  // 5: vibe.v1.StartResponse.status:type_name -> vibe.v1.Status
	2,  // 6: vibe.v1.StartResponse.frontend:type_name -> vibe.v1.FrontendInfo
	0,  // 7: vibe.v1.StopResponse.status:type_name -> vibe.v1.Status
	3,  // 8: vibe.v1.ControlService.Status:input_type -> vibe.v1.StatusRequest
	5,  // 9: vibe.v1.ControlService.ListProfiles:input_type -> vibe.v1.ListProfilesRequest
	7,  // 10: vibe.v1.ControlService.Start:input_type -> vibe.v1.StartRequest
	9,  // 11: vibe.v1.ControlService.Stop:input_type -> vibe.v1.StopRequest
	11, // 12: vibe.v1.ControlService.Shutdown:input_type -> vibe.v1.ShutdownRequest
	13, // 13: vibe.v1.ControlService.Logs:input_type -> vibe.v1.LogsRequest
	4,  // 14: vibe.v1.ControlService.Status:output_type -> vibe.v1.StatusResponse
	6,  // 15: vibe.v1.ControlService.ListProfiles:output_type -> vibe.v1.ListProfilesResponse
	8,  // 16: vibe.v1.ControlService.Start:output_type -> vibe.v1.StartResponse
	10, // 17: vibe.v1.ControlService.Stop:output_type -> vibe.v1.StopResponse
	12, // 18: vibe.v1.ControlService.Shutdown:output_type -> vibe.v1.ShutdownResponse
	14, // 19: vibe.v1.ControlService.Logs:output_type -> vibe.v1.LogsResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_vibe_v1_control_proto_init() }
func file_vibe_v1_control_proto_init() {
	if File_vibe_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vibe_v1_control_proto_rawDesc), len(file_vibe_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vibe_v1_control_proto_goTypes,
		DependencyIndexes: file_vibe_v1_control_proto_depIdxs,
		MessageInfos:      file_vibe_v1_control_proto_msgTypes,
	}.Build()
	File_vibe_v1_control_proto = out.File
	file_vibe_v1_control_proto_goTypes = nil
	file_vibe_v1_control_proto_depIdxs = nil
}
