// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vibe/v1/control.proto

package vibev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullProgress_Phase int32

const (
	PullProgress_PHASE_UNSPECIFIED PullProgress_Phase = 0
	PullProgress_PHASE_RESOLVING   PullProgress_Phase = 1 // HEAD request to HuggingFace to fetch metadata
	PullProgress_PHASE_DOWNLOADING PullProgress_Phase = 2 // bytes flowing in
	PullProgress_PHASE_VERIFYING   PullProgress_Phase = 3 // post-download size check
	PullProgress_PHASE_DONE        PullProgress_Phase = 4 // final state
)

// Enum value maps for PullProgress_Phase.
var (
	PullProgress_Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_RESOLVING",
		2: "PHASE_DOWNLOADING",
		3: "PHASE_VERIFYING",
		4: "PHASE_DONE",
	}
	PullProgress_Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_RESOLVING":   1,
		"PHASE_DOWNLOADING": 2,
		"PHASE_VERIFYING":   3,
		"PHASE_DONE":        4,
	}
)

func (x PullProgress_Phase) Enum() *PullProgress_Phase {
	p := new(PullProgress_Phase)
	*p = x
	return p
}

func (x PullProgress_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullProgress_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_vibe_v1_control_proto_enumTypes[0].Descriptor()
}

func (PullProgress_Phase) Type() protoreflect.EnumType {
	return &file_vibe_v1_control_proto_enumTypes[0]
}

func (x PullProgress_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullProgress_Phase.Descriptor instead.
func (PullProgress_Phase) EnumDescriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{23, 0}
}

type Status struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Running     bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Ready       bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Profile     string                 `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	BackendAddr string                 `protobuf:"bytes,5,opt,name=backend_addr,json=backendAddr,proto3" json:"backend_addr,omitempty"`
	ProxyAddr   string                 `protobuf:"bytes,6,opt,name=proxy_addr,json=proxyAddr,proto3" json:"proxy_addr,omitempty"`
	Pid         int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	// frontend_env carries the env vars the user should set when launching the
	// external frontend, so `vibe env` can echo them after the fact.
	FrontendEnv map[string]string `protobuf:"bytes,8,rep,name=frontend_env,json=frontendEnv,proto3" json:"frontend_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// parallel reports the active profile's llama_server `parallel` setting:
	// the number of concurrent inference slots the backend exposes. Zero when
	// no profile is active or the active profile uses a non-llama_server
	// backend (the parallel concept is llama-server-specific). Clients use
	// this to cap their own foreach/fan-out concurrency to the actual
	// back-pressure point instead of spinning N goroutines that all queue
	// on the same serialized inference slot.
	Parallel      int32 `protobuf:"varint,9,opt,name=parallel,proto3" json:"parallel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_vibe_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *Status) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Status) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Status) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Status) GetBackendAddr() string {
	if x != nil {
		return x.BackendAddr
	}
	return ""
}

func (x *Status) GetProxyAddr() string {
	if x != nil {
		return x.ProxyAddr
	}
	return ""
}

func (x *Status) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Status) GetFrontendEnv() map[string]string {
	if x != nil {
		return x.FrontendEnv
	}
	return nil
}

func (x *Status) GetParallel() int32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_vibe_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Profile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FrontendInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WroteFile       string                 `protobuf:"bytes,2,opt,name=wrote_file,json=wroteFile,proto3" json:"wrote_file,omitempty"`
	RestartRequired bool                   `protobuf:"varint,3,opt,name=restart_required,json=restartRequired,proto3" json:"restart_required,omitempty"`
	// env_vars the user should set when launching the external frontend.
	// Example: {"OPENCODE_CONFIG": "/home/.../state/vibe/frontend/code/opencode.json"}.
	EnvVars map[string]string `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// kind echoes profile.Frontend.Kind so the CLI can word its output
	// differently for external (config written, user launches binary) vs
	// managed/docker-compose (vibe also launched the binary).
	Kind string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	// url is the address the user should open in their browser, derived
	// from profile.Frontend.BrowserURL() (explicit frontend.url field or
	// the wait_for entry with a "/" path). Empty when neither applies —
	// the CLI omits the browser hint in that case.
	Url string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	// args is frontend.Args with ${VAR} placeholders already expanded (e.g.
	// ${MODEL_ALIAS} -> the resolved canonical model id). Only populated for
	// kind=managed foreground activations (`vibe run`) — that's the one path
	// where the CLI itself execs the binary and must not re-derive expansion
	// client-side (it doesn't have the daemon's ExpandContext).
	Args          []string `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendInfo) Reset() {
	*x = FrontendInfo{}
	mi := &file_vibe_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendInfo) ProtoMessage() {}

func (x *FrontendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendInfo.ProtoReflect.Descriptor instead.
func (*FrontendInfo) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *FrontendInfo) GetWroteFile() string {
	if x != nil {
		return x.WroteFile
	}
	return ""
}

func (x *FrontendInfo) GetRestartRequired() bool {
	if x != nil {
		return x.RestartRequired
	}
	return false
}

func (x *FrontendInfo) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *FrontendInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FrontendInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FrontendInfo) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{3}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status describes the currently-active profile (empty Status block
	// when no active profile is running). Backward-compatible with
	// pre-services clients that only knew about the single active slot.
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// services lists every running service-mode profile. Service-mode
	// profiles run alongside one another and alongside the active
	// profile (each has its own supervisor instance + published port).
	Services      []*Status `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatusResponse) GetServices() []*Status {
	if x != nil {
		return x.Services
	}
	return nil
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{5}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ListProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type StartRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Profile string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	// no_vram_check, when true, skips the pre-flight VRAM check the daemon
	// performs against the profile's estimated_vram_gb. For users who know
	// their setup better than the heuristic.
	NoVramCheck bool `protobuf:"varint,2,opt,name=no_vram_check,json=noVramCheck,proto3" json:"no_vram_check,omitempty"`
	// foreground, when true, asks the daemon to render the frontend's config
	// file and expand its env, but NOT spawn the frontend binary. The caller
	// (typically `vibe run`) then exec's the binary in its own terminal so
	// TUI tools like opencode get attached stdio. The daemon ignores this
	// flag for kind=external (already config-only) and rejects it for
	// kind=docker-compose (compose is inherently supervised).
	Foreground bool `protobuf:"varint,3,opt,name=foreground,proto3" json:"foreground,omitempty"`
	// backend activates a named backend definition (backends/<name>.yaml) as
	// the active model server with NO frontend — the model is the deliverable,
	// reached via the proxy. Used by vamp capability resolution so a pipeline
	// depends on a backend, not a frontend-bearing profile. Exactly one of
	// profile or backend must be set. The active identity is the backend name,
	// so repeated activations of the same backend are no-op reuse.
	Backend       string `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *StartRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *StartRequest) GetNoVramCheck() bool {
	if x != nil {
		return x.NoVramCheck
	}
	return false
}

func (x *StartRequest) GetForeground() bool {
	if x != nil {
		return x.Foreground
	}
	return false
}

func (x *StartRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Frontend      *FrontendInfo          `protobuf:"bytes,2,opt,name=frontend,proto3" json:"frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *StartResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StartResponse) GetFrontend() *FrontendInfo {
	if x != nil {
		return x.Frontend
	}
	return nil
}

type StopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// profile, if set, names the specific profile to stop. Service-mode
	// profiles must be addressed by name (e.g. `vibe stop searxng`)
	// since multiple can run concurrently. If empty, the daemon stops
	// the active profile (legacy single-profile behavior).
	//
	// The special value "all" stops the active profile and every
	// running service in one call — useful in shutdown / reset paths.
	Profile       string `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *StopRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *StopResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{11}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{12}
}

type LogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// profile, if set, requests logs for a specific service-mode
	// profile (matching its profile.name). Empty / "active" → the
	// active profile (legacy behavior).
	Profile       string `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *LogsRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *LogsResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *PullRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type CellDrainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reason/eta are the declared intent ("gaming, back ~23:00") recorded
	// alongside the drain — for humans and agents asking why, never for
	// routing. Both optional.
	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Eta    string `protobuf:"bytes,2,opt,name=eta,proto3" json:"eta,omitempty"`
	// wait_seconds bounds a quiescence wait before the drain command runs:
	// llama-swap's SIGTERM path cancels in-flight streams immediately
	// (v239 verified — CloseStreams precedes the graceful drain), so the
	// only way a generation completes across a drain is to let it finish
	// FIRST. 0 (default) drains immediately; in-flight requests then die
	// truncated, which the report's in_flight_requests field warned about.
	WaitSeconds   int32 `protobuf:"varint,3,opt,name=wait_seconds,json=waitSeconds,proto3" json:"wait_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellDrainRequest) Reset() {
	*x = CellDrainRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellDrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellDrainRequest) ProtoMessage() {}

func (x *CellDrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellDrainRequest.ProtoReflect.Descriptor instead.
func (*CellDrainRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *CellDrainRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CellDrainRequest) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

func (x *CellDrainRequest) GetWaitSeconds() int32 {
	if x != nil {
		return x.WaitSeconds
	}
	return 0
}

// LeaseView is one advisory lease as shown in the pre-drain report: a
// consumer's "I hold this model mid-batch" note. Advisory only — never
// blocks anything.
type LeaseView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          string                 `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Holder        string                 `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseView) Reset() {
	*x = LeaseView{}
	mi := &file_vibe_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseView) ProtoMessage() {}

func (x *LeaseView) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseView.ProtoReflect.Descriptor instead.
func (*LeaseView) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *LeaseView) GetCell() string {
	if x != nil {
		return x.Cell
	}
	return ""
}

func (x *LeaseView) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LeaseView) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LeaseView) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *LeaseView) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// CellDrainResponse is the pre-drain report: what the cell was doing when
// the drain fired.
type CellDrainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resident_models are the models llama-swap had loaded (any non-stopped
	// state) at drain time.
	ResidentModels []string `protobuf:"bytes,1,rep,name=resident_models,json=residentModels,proto3" json:"resident_models,omitempty"`
	// in_flight_requests is llama-swap's reported in-flight count, present
	// only when the cell's /api/metrics answers — /running carries no
	// request counts, and inventing them is worse than omitting the field.
	InFlightRequests *int64 `protobuf:"varint,2,opt,name=in_flight_requests,json=inFlightRequests,proto3,oneof" json:"in_flight_requests,omitempty"`
	// active_leases are the fleet's advisory leases naming this cell,
	// fetched from fleetd when a registry is configured (empty otherwise).
	ActiveLeases []*LeaseView `protobuf:"bytes,3,rep,name=active_leases,json=activeLeases,proto3" json:"active_leases,omitempty"`
	// leases_unavailable is true when the lease fetch itself failed — the
	// drain still proceeded (leases are advisory), but the caller knows the
	// report can't rule out stranded work.
	LeasesUnavailable bool `protobuf:"varint,4,opt,name=leases_unavailable,json=leasesUnavailable,proto3" json:"leases_unavailable,omitempty"`
	// wait_status reports what became of a requested quiescence wait:
	// "not_requested" (wait_seconds was 0), "waited" (the cell reported
	// in-flight counts and reached zero), or "skipped_no_inflight_data"
	// (nothing ever reported a count, so the drain ran immediately). An
	// operator who asked for quiescence and silently got a stream-
	// cancelling drain has to be able to see that.
	WaitStatus    *string `protobuf:"bytes,5,opt,name=wait_status,json=waitStatus,proto3,oneof" json:"wait_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellDrainResponse) Reset() {
	*x = CellDrainResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellDrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellDrainResponse) ProtoMessage() {}

func (x *CellDrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellDrainResponse.ProtoReflect.Descriptor instead.
func (*CellDrainResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *CellDrainResponse) GetResidentModels() []string {
	if x != nil {
		return x.ResidentModels
	}
	return nil
}

func (x *CellDrainResponse) GetInFlightRequests() int64 {
	if x != nil && x.InFlightRequests != nil {
		return *x.InFlightRequests
	}
	return 0
}

func (x *CellDrainResponse) GetActiveLeases() []*LeaseView {
	if x != nil {
		return x.ActiveLeases
	}
	return nil
}

func (x *CellDrainResponse) GetLeasesUnavailable() bool {
	if x != nil {
		return x.LeasesUnavailable
	}
	return false
}

func (x *CellDrainResponse) GetWaitStatus() string {
	if x != nil && x.WaitStatus != nil {
		return *x.WaitStatus
	}
	return ""
}

type CellResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellResumeRequest) Reset() {
	*x = CellResumeRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellResumeRequest) ProtoMessage() {}

func (x *CellResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellResumeRequest.ProtoReflect.Descriptor instead.
func (*CellResumeRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{19}
}

type CellResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellResumeResponse) Reset() {
	*x = CellResumeResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellResumeResponse) ProtoMessage() {}

func (x *CellResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellResumeResponse.ProtoReflect.Descriptor instead.
func (*CellResumeResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{20}
}

type CellSuspendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reason is the declared intent recorded alongside the suspend
	// ("asleep per sleep_schedule"), for humans and agents asking why.
	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// require_idle refuses the suspend unless this cell can PROVE it is
	// idle: a non-zero in-flight count and an UNREPORTED one both refuse,
	// because unknown is not zero on the receiving side either. fleetd's
	// scheduled path always sets it; an operator's explicit --force does
	// not, since an operator asking is not fleetd guessing.
	RequireIdle   bool `protobuf:"varint,2,opt,name=require_idle,json=requireIdle,proto3" json:"require_idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellSuspendRequest) Reset() {
	*x = CellSuspendRequest{}
	mi := &file_vibe_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellSuspendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellSuspendRequest) ProtoMessage() {}

func (x *CellSuspendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellSuspendRequest.ProtoReflect.Descriptor instead.
func (*CellSuspendRequest) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *CellSuspendRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CellSuspendRequest) GetRequireIdle() bool {
	if x != nil {
		return x.RequireIdle
	}
	return false
}

type CellSuspendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resident_models are the models llama-swap had loaded at suspend time
	// — the same pre-verb report CellDrain gives, for the same reason.
	ResidentModels []string `protobuf:"bytes,1,rep,name=resident_models,json=residentModels,proto3" json:"resident_models,omitempty"`
	// in_flight_requests is present only when the cell's inflight tracking
	// has reported; absent means unknown, never zero.
	InFlightRequests *int64 `protobuf:"varint,2,opt,name=in_flight_requests,json=inFlightRequests,proto3,oneof" json:"in_flight_requests,omitempty"`
	// idle_status is what became of the idle proof: "not_required" or
	// "verified_idle".
	IdleStatus    string `protobuf:"bytes,3,opt,name=idle_status,json=idleStatus,proto3" json:"idle_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellSuspendResponse) Reset() {
	*x = CellSuspendResponse{}
	mi := &file_vibe_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellSuspendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellSuspendResponse) ProtoMessage() {}

func (x *CellSuspendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellSuspendResponse.ProtoReflect.Descriptor instead.
func (*CellSuspendResponse) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *CellSuspendResponse) GetResidentModels() []string {
	if x != nil {
		return x.ResidentModels
	}
	return nil
}

func (x *CellSuspendResponse) GetInFlightRequests() int64 {
	if x != nil && x.InFlightRequests != nil {
		return *x.InFlightRequests
	}
	return 0
}

func (x *CellSuspendResponse) GetIdleStatus() string {
	if x != nil {
		return x.IdleStatus
	}
	return ""
}

type PullProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Phase           PullProgress_Phase     `protobuf:"varint,1,opt,name=phase,proto3,enum=vibe.v1.PullProgress_Phase" json:"phase,omitempty"`
	DownloadedBytes int64                  `protobuf:"varint,2,opt,name=downloaded_bytes,json=downloadedBytes,proto3" json:"downloaded_bytes,omitempty"`
	TotalBytes      int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// human-readable message, e.g. "resuming from byte 1234567"
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullProgress) Reset() {
	*x = PullProgress{}
	mi := &file_vibe_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullProgress) ProtoMessage() {}

func (x *PullProgress) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullProgress.ProtoReflect.Descriptor instead.
func (*PullProgress) Descriptor() ([]byte, []int) {
	return file_vibe_v1_control_proto_rawDescGZIP(), []int{23}
}

func (x *PullProgress) GetPhase() PullProgress_Phase {
	if x != nil {
		return x.Phase
	}
	return PullProgress_PHASE_UNSPECIFIED
}

func (x *PullProgress) GetDownloadedBytes() int64 {
	if x != nil {
		return x.DownloadedBytes
	}
	return 0
}

func (x *PullProgress) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *PullProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_vibe_v1_control_proto protoreflect.FileDescriptor

const file_vibe_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x15vibe/v1/control.proto\x12\avibe.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x03\n" +
	"\x06Status\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12!\n" +
	"\fbackend_addr\x18\x05 \x01(\tR\vbackendAddr\x12\x1d\n" +
	"\n" +
	"proxy_addr\x18\x06 \x01(\tR\tproxyAddr\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12C\n" +
	"\ffrontend_env\x18\b \x03(\v2 .vibe.v1.Status.FrontendEnvEntryR\vfrontendEnv\x12\x1a\n" +
	"\bparallel\x18\t \x01(\x05R\bparallel\x1a>\n" +
	"\x10FrontendEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\x98\x02\n" +
	"\fFrontendInfo\x12\x1d\n" +
	"\n" +
	"wrote_file\x18\x02 \x01(\tR\twroteFile\x12)\n" +
	"\x10restart_required\x18\x03 \x01(\bR\x0frestartRequired\x12=\n" +
	"\benv_vars\x18\x04 \x03(\v2\".vibe.v1.FrontendInfo.EnvVarsEntryR\aenvVars\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x12\n" +
	"\x04args\x18\a \x03(\tR\x04args\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02R\x03app\"\x0f\n" +
	"\rStatusRequest\"f\n" +
	"\x0eStatusResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.vibe.v1.StatusR\x06status\x12+\n" +
	"\bservices\x18\x02 \x03(\v2\x0f.vibe.v1.StatusR\bservices\"\x15\n" +
	"\x13ListProfilesRequest\"D\n" +
	"\x14ListProfilesResponse\x12,\n" +
	"\bprofiles\x18\x01 \x03(\v2\x10.vibe.v1.ProfileR\bprofiles\"\x86\x01\n" +
	"\fStartRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\"\n" +
	"\rno_vram_check\x18\x02 \x01(\bR\vnoVramCheck\x12\x1e\n" +
	"\n" +
	"foreground\x18\x03 \x01(\bR\n" +
	"foreground\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\"k\n" +
	"\rStartResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.vibe.v1.StatusR\x06status\x121\n" +
	"\bfrontend\x18\x02 \x01(\v2\x15.vibe.v1.FrontendInfoR\bfrontend\"'\n" +
	"\vStopRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"7\n" +
	"\fStopResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.vibe.v1.StatusR\x06status\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"'\n" +
	"\vLogsRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"$\n" +
	"\fLogsResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\"'\n" +
	"\vPullRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"_\n" +
	"\x10CellDrainRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x10\n" +
	"\x03eta\x18\x02 \x01(\tR\x03eta\x12!\n" +
	"\fwait_seconds\x18\x03 \x01(\x05R\vwaitSeconds\"\x9c\x01\n" +
	"\tLeaseView\x12\x12\n" +
	"\x04cell\x18\x01 \x01(\tR\x04cell\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06holder\x18\x03 \x01(\tR\x06holder\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa4\x02\n" +
	"\x11CellDrainResponse\x12'\n" +
	"\x0fresident_models\x18\x01 \x03(\tR\x0eresidentModels\x121\n" +
	"\x12in_flight_requests\x18\x02 \x01(\x03H\x00R\x10inFlightRequests\x88\x01\x01\x127\n" +
	"\ractive_leases\x18\x03 \x03(\v2\x12.vibe.v1.LeaseViewR\factiveLeases\x12-\n" +
	"\x12leases_unavailable\x18\x04 \x01(\bR\x11leasesUnavailable\x12$\n" +
	"\vwait_status\x18\x05 \x01(\tH\x01R\n" +
	"waitStatus\x88\x01\x01B\x15\n" +
	"\x13_in_flight_requestsB\x0e\n" +
	"\f_wait_status\"\x13\n" +
	"\x11CellResumeRequest\"\x14\n" +
	"\x12CellResumeResponse\"O\n" +
	"\x12CellSuspendRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12!\n" +
	"\frequire_idle\x18\x02 \x01(\bR\vrequireIdle\"\xa9\x01\n" +
	"\x13CellSuspendResponse\x12'\n" +
	"\x0fresident_models\x18\x01 \x03(\tR\x0eresidentModels\x121\n" +
	"\x12in_flight_requests\x18\x02 \x01(\x03H\x00R\x10inFlightRequests\x88\x01\x01\x12\x1f\n" +
	"\vidle_status\x18\x03 \x01(\tR\n" +
	"idleStatusB\x15\n" +
	"\x13_in_flight_requests\"\x98\x02\n" +
	"\fPullProgress\x121\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1b.vibe.v1.PullProgress.PhaseR\x05phase\x12)\n" +
	"\x10downloaded_bytes\x18\x02 \x01(\x03R\x0fdownloadedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"o\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPHASE_RESOLVING\x10\x01\x12\x15\n" +
	"\x11PHASE_DOWNLOADING\x10\x02\x12\x13\n" +
	"\x0fPHASE_VERIFYING\x10\x03\x12\x0e\n" +
	"\n" +
	"PHASE_DONE\x10\x042\x9b\x05\n" +
	"\x0eControlService\x12;\n" +
	"\x06Status\x12\x16.vibe.v1.StatusRequest\x1a\x17.vibe.v1.StatusResponse\"\x00\x12M\n" +
	"\fListProfiles\x12\x1c.vibe.v1.ListProfilesRequest\x1a\x1d.vibe.v1.ListProfilesResponse\"\x00\x128\n" +
	"\x05Start\x12\x15.vibe.v1.StartRequest\x1a\x16.vibe.v1.StartResponse\"\x00\x125\n" +
	"\x04Stop\x12\x14.vibe.v1.StopRequest\x1a\x15.vibe.v1.StopResponse\"\x00\x12A\n" +
	"\bShutdown\x12\x18.vibe.v1.ShutdownRequest\x1a\x19.vibe.v1.ShutdownResponse\"\x00\x125\n" +
	"\x04Logs\x12\x14.vibe.v1.LogsRequest\x1a\x15.vibe.v1.LogsResponse\"\x00\x127\n" +
	"\x04Pull\x12\x14.vibe.v1.PullRequest\x1a\x15.vibe.v1.PullProgress\"\x000\x01\x12D\n" +
	"\tCellDrain\x12\x19.vibe.v1.CellDrainRequest\x1a\x1a.vibe.v1.CellDrainResponse\"\x00\x12G\n" +
	"\n" +
	"CellResume\x12\x1a.vibe.v1.CellResumeRequest\x1a\x1b.vibe.v1.CellResumeResponse\"\x00\x12J\n" +
	"\vCellSuspend\x12\x1b.vibe.v1.CellSuspendRequest\x1a\x1c.vibe.v1.CellSuspendResponse\"\x00B7Z5github.com/gallowaysoftware/vibe/proto/vibe/v1;vibev1b\x06proto3"

var (
	file_vibe_v1_control_proto_rawDescOnce sync.Once
	file_vibe_v1_control_proto_rawDescData []byte
)

func file_vibe_v1_control_proto_rawDescGZIP() []byte {
	file_vibe_v1_control_proto_rawDescOnce.Do(func() {
		file_vibe_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vibe_v1_control_proto_rawDesc), len(file_vibe_v1_control_proto_rawDesc)))
	})
	return file_vibe_v1_control_proto_rawDescData
}

var file_vibe_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vibe_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_vibe_v1_control_proto_goTypes = []any{
	(PullProgress_Phase)(0),       // 0: vibe.v1.PullProgress.Phase
	(*Status)(nil),                // 1: vibe.v1.Status
	(*Profile)(nil),               // 2: vibe.v1.Profile
	(*FrontendInfo)(nil),          // 3: vibe.v1.FrontendInfo
	(*StatusRequest)(nil),         // 4: vibe.v1.StatusRequest
	(*StatusResponse)(nil),        // 5: vibe.v1.StatusResponse
	(*ListProfilesRequest)(nil),   // 6: vibe.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),  // 7: vibe.v1.ListProfilesResponse
	(*StartRequest)(nil),          // 8: vibe.v1.StartRequest
	(*StartResponse)(nil),         // 9: vibe.v1.StartResponse
	(*StopRequest)(nil),           // 10: vibe.v1.StopRequest
	(*StopResponse)(nil),          // 11: vibe.v1.StopResponse
	(*ShutdownRequest)(nil),       // 12: vibe.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 13: vibe.v1.ShutdownResponse
	(*LogsRequest)(nil),           // 14: vibe.v1.LogsRequest
	(*LogsResponse)(nil),          // 15: vibe.v1.LogsResponse
	(*PullRequest)(nil),           // 16: vibe.v1.PullRequest
	(*CellDrainRequest)(nil),      // 17: vibe.v1.CellDrainRequest
	(*LeaseView)(nil),             // 18: vibe.v1.LeaseView
	(*CellDrainResponse)(nil),     // 19: vibe.v1.CellDrainResponse
	(*CellResumeRequest)(nil),     // 20: vibe.v1.CellResumeRequest
	(*CellResumeResponse)(nil),    // 21: vibe.v1.CellResumeResponse
	(*CellSuspendRequest)(nil),    // 22: vibe.v1.CellSuspendRequest
	(*CellSuspendResponse)(nil),   // 23: vibe.v1.CellSuspendResponse
	(*PullProgress)(nil),          // 24: vibe.v1.PullProgress
	nil,                           // 25: vibe.v1.Status.FrontendEnvEntry
	nil,                           // 26: vibe.v1.FrontendInfo.EnvVarsEntry
	(*timestamppb.Timestamp)(nil), // 27: google.protobuf.Timestamp
}
var file_vibe_v1_control_proto_depIdxs = []int32{
	27, // 0: vibe.v1.Status.started_at:type_name -> google.protobuf.Timestamp
	25, // 1: vibe.v1.Status.frontend_env:type_name -> vibe.v1.Status.FrontendEnvEntry
	26, // 2: vibe.v1.FrontendInfo.env_vars:type_name -> vibe.v1.FrontendInfo.EnvVarsEntry
	1,  // 3: vibe.v1.StatusResponse.status:type_name -> vibe.v1.Status
	1,  // 4: vibe.v1.StatusResponse.services:type_name -> vibe.v1.Status
	2,  // 5: vibe.v1.ListProfilesResponse.profiles:type_name -> vibe.v1.Profile
	1,  // 6: vibe.v1.StartResponse.status:type_name -> vibe.v1.Status
	3,  // 7: vibe.v1.StartResponse.frontend:type_name -> vibe.v1.FrontendInfo
	1,  // 8: vibe.v1.StopResponse.status:type_name -> vibe.v1.Status
	27, // 9: vibe.v1.LeaseView.expires_at:type_name -> google.protobuf.Timestamp
	18, // 10: vibe.v1.CellDrainResponse.active_leases:type_name -> vibe.v1.LeaseView
	0,  // 11: vibe.v1.PullProgress.phase:type_name -> vibe.v1.PullProgress.Phase
	4,  // 12: vibe.v1.ControlService.Status:input_type -> vibe.v1.StatusRequest
	6,  // 13: vibe.v1.ControlService.ListProfiles:input_type -> vibe.v1.ListProfilesRequest
	8,  // 14: vibe.v1.ControlService.Start:input_type -> vibe.v1.StartRequest
	10, // 15: vibe.v1.ControlService.Stop:input_type -> vibe.v1.StopRequest
	12, // 16: vibe.v1.ControlService.Shutdown:input_type -> vibe.v1.ShutdownRequest
	14, // 17: vibe.v1.ControlService.Logs:input_type -> vibe.v1.LogsRequest
	16, // 18: vibe.v1.ControlService.Pull:input_type -> vibe.v1.PullRequest
	17, // 19: vibe.v1.ControlService.CellDrain:input_type -> vibe.v1.CellDrainRequest
	20, // 20: vibe.v1.ControlService.CellResume:input_type -> vibe.v1.CellResumeRequest
	22, // 21: vibe.v1.ControlService.CellSuspend:input_type -> vibe.v1.CellSuspendRequest
	5,  // 22: vibe.v1.ControlService.Status:output_type -> vibe.v1.StatusResponse
	7,  // 23: vibe.v1.ControlService.ListProfiles:output_type -> vibe.v1.ListProfilesResponse
	9,  // 24: vibe.v1.ControlService.Start:output_type -> vibe.v1.StartResponse
	11, // 25: vibe.v1.ControlService.Stop:output_type -> vibe.v1.StopResponse
	13, // 26: vibe.v1.ControlService.Shutdown:output_type -> vibe.v1.ShutdownResponse
	15, // 27: vibe.v1.ControlService.Logs:output_type -> vibe.v1.LogsResponse
	24, // 28: vibe.v1.ControlService.Pull:output_type -> vibe.v1.PullProgress
	19, // 29: vibe.v1.ControlService.CellDrain:output_type -> vibe.v1.CellDrainResponse
	21, // 30: vibe.v1.ControlService.CellResume:output_type -> vibe.v1.CellResumeResponse
	23, // 31: vibe.v1.ControlService.CellSuspend:output_type -> vibe.v1.CellSuspendResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_vibe_v1_control_proto_init() }
func file_vibe_v1_control_proto_init() {
	if File_vibe_v1_control_proto != nil {
		return
	}
	file_vibe_v1_control_proto_msgTypes[18].OneofWrappers = []any{}
	file_vibe_v1_control_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vibe_v1_control_proto_rawDesc), len(file_vibe_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vibe_v1_control_proto_goTypes,
		DependencyIndexes: file_vibe_v1_control_proto_depIdxs,
		EnumInfos:         file_vibe_v1_control_proto_enumTypes,
		MessageInfos:      file_vibe_v1_control_proto_msgTypes,
	}.Build()
	File_vibe_v1_control_proto = out.File
	file_vibe_v1_control_proto_goTypes = nil
	file_vibe_v1_control_proto_depIdxs = nil
}
